### PR TITLE
add light/dark color modes for the canvas

### PR DESCRIPTION
**Pull request by zhouhaoyiu**
#3

### CODE REVIEW

**Comment by ggorlen** [comment]
Thanks for the PR! Giving users a bit more color control makes sense, but I think I'd prefer to simply add the stroke color as a parameter and leave concepts like "night mode" up to the client code to define as they see fit, rather than baking them into the PBT interface. 

But then the font should probably be a parameter as well... Then there are enough parameters that it should probably be a config object. So it's a bit of a slippery slope, and my original intent wasn't to provide a huge array of options/features, just a quick n' dirty viz.

**Comment by zhouhaoyiu** [comment]
How about this commit？
test

**Comment by zhouhaoyiu** [comment]
I tested the export function and it seems to work

P. S:
Currently, the function of getinvertcolor only supports complete hexadecimal color codes and I add a validator.

I don't think we need to worry about a large number of parameters. We can add presets so that people can use them easily

**Comment by ggorlen** [comment]
Something like this should work. I'll take a closer look at the code and make a few tweaks when I get the chance.

**Comment by zhouhaoyiu** [comment]
Thanks and I created branch named url in my fork repository that can parse URL parameters.

The contact in your homepage is gsgorlen@gmail.com? Can I make friends with you ? 😄😄😄

**Comment by ggorlen** [comment]
Thanks again for the PR and apologies for the long delay. I decided to deal with the color problem in a different way using an options object (see https://github.com/ggorlen/prettybt/pull/8), but this was helpful to provide ideas, some of which I'd like to revisit in the future.

**Pull request closed without merging**
